version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sulwork
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    # Ajuste para o seu backend (path ou imagem)
    image: sulwork-backend:latest
    # build:
    #   context: ../backend
    #   dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sulwork
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://backend:8080
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  pgdata:
