services:
  postgres:
    image: postgres:latest
    container_name: DB
    environment:
      POSTGRES_DB: breakfast
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    restart: always
